### ISSUE TITLE
建议：能支持git吗，比如和昨天，上周相比，我工作了多少行代码，毕竟有一个项目的迭代的场景

### ISSUE THREAD

**Issue by lcoder** [jkpang/PPRows#10]
RT

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo作者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA
