### ISSUE TITLE
是不是缺少了一个库文件？

### ISSUE THREAD

**Issue by qtechdrew** [jkpang/PPRows#2]
ld: warning: directory not found for option '-L/Users/deadroach/Library/Developer/Xcode/DerivedData/PPRows-ebfuxlgeownhoqfhrkwexpccaaxo/Build/Products/Debug/PPCounter'
ld: library not found for -lPPCounter
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jkpang** [comment]
没有吧, 从Github上下载下来直接就可以运行的,现在解决了吗? @qtechdrew

**Comment by qtechdrew** [comment]
解决了，老长时间没用cocopods了，忘记得用那个白色的文件打开工程了😓

**Comment by jkpang** [comment]
解决了就好👌
